server.port=${PORT:8080}
spring.application.name=agentpay

# ================= POSTGRESQL DATABASE CONFIGURATION =================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/agentpay_db}
spring.datasource.username=${DB_USERNAME:postgres}
# Put your actual pgAdmin password here:
spring.datasource.password=${DB_PASSWORD:dileep@99}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SMART CLOUD RESILIENCE:
# Connects to pgAdmin on your laptop, but DOES NOT crash Render if database is unattached
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=3000

# ================= RAZORPAY TEST CREDENTIALS =================
razorpay.key.id=rzp_test_1DP5mmOlF5G5ag
razorpay.key.secret=s2gQhLkJlq7z2UoV5f7W3w6a

# ================= REAL GMAIL SMTP CONFIGURATION =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Put your real Gmail address below:
spring.mail.username=dileepchowdary99gonuguntla@gmail.com
# Your generated 16-letter App Password:
spring.mail.password=jiehgrhqfyejqyqn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000

spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Google Webhook for HTTPS Cloud Email (Works 100% on Render & Localhost)
mail.webhook.url=https://script.google.com/macros/s/AKfycbx7d2O8o4nrt-eiq7SrZQbIonpBXwWlcZGckPgZQ_RIR1mYrPocyObihpcgjv-7Ms8_3Q/exec